
env:
  matrix:
    - TARGET="wovnphp"
    - TARGET="wovnphp-cakephp"
    - TARGET="wovnphp-wordpress"
    - TARGET="wovnjava"
    - TARGET="wovnwp"

language: minimal

services:
  - docker

script:
  - cd $TARGET
  - make
  - id
  - "ls -al app/webroot"
  - docker-compose up -d
  - docker-compose down -v
  - make clean
